name: Release
permissions:
  contents: write
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print the changelog
        run: echo "${{ steps.changelog.outputs.tag }}"

      - name: Print the changelog
        run: echo "${{ steps.changelog.outputs.version }}"

      - name: Print the changelog
        run: echo "${{ steps.changelog.outputs.clean_changelog }}" > notes.text

      - name: Create Release
        run: gh release create ${{ steps.changelog.outputs.tag  }} --notes-file notes.text
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}