name: Release
permissions:
  contents: write
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-count: "0"

      - name: Print the changelog
        run: echo "${{ steps.changelog.outputs.tag }}"

      - name: Print the changelog
        run: echo "${{ steps.changelog.outputs.version }}"

      - name: Print the changelog
        run: echo "${{ steps.changelog.outputs.clean_changelog }}" > notes.text

      - name: Create Release
        run: gh release create ${{ steps.changelog.outputs.tag  }} --notes-file notes.text
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: install
        run: npm install

      - name: Build
        run: make build

      - name: Rsync
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -a
          path: dist/
          remote_path: "/var/www/html/dev.io37.ch"
          remote_host: dev.io37.ch
          remote_user: deploy
          remote_key: ${{ secrets.DEPLOY_KEY }}
