name: Test
on:
  push:
    branches-ignore:
      - main

jobs:
  macbook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: installs the site
        run: npm install

      - name: Build
        run: make build

      - name: Rsync
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -a
          path: dist/
          remote_path: "/var/www/html/asda.io37.ch"
          remote_host: dev.io37.ch
          remote_user: deploy
          remote_key: ${{ secrets.DEPLOY_KEY }}
