name: Test
on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: installs the site
        run: npm install

      - name: Build
        run: make build

      - name: Create branch.html
        run: |
          cp .github/templates/branch.html dist/branch.html
          cp .github/templates/workflow.css dist/workflow.css
          sed -i 's|\[REPO_NAME\]|'"$GITHUB_REPOSITORY"'|g' dist/branch.html
          sed -i 's|\[BRANCH_NAME\]|'"$(echo $GITHUB_REF | sed 's|refs/heads/||')"'|g' dist/branch.html
          sed -i 's|\[DATE\]|'"$(date)"'|g' dist/branch.html

      - name: Rsync
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -a
          path: dist/
          remote_path: "/var/www/html/asda.io37.ch"
          remote_host: dev.io37.ch
          remote_user: deploy
          remote_key: ${{ secrets.DEPLOY_KEY }}
